- name: Download and unarchive driver
  unarchive:
    src: https://github.com/intel/linux-sgx-driver/archive/refs/tags/sgx_diver_{{ driver_version }}.tar.gz
    dest: /tmp
    remote_src: yes

- name: Build the driver
  make:
    chdir: /tmp/linux-sgx-driver-sgx_diver_{{ driver_version }}/

- name: Create kernel driver directory
  file:
      path: /lib/modules/{{ ansible_kerne l}}/kernel/drivers/intel/sgx
      state: directory
      recurse: yes

- name: Copy isgx.ko to kernel driver directory
  copy:
    src: /tmp/linux-sgx-driver-sgx_diver_{{ driver_version }}/isgx.ko
    dest: /lib/modules/{{ ansible_kernel }}/kernel/drivers/intel/sgx/isgx.ko
    remote_src: yes

- name: Add isgx in /etc/modules
  lineinfile:
    path: /etc/modules
    regexp: '^isgx$'
    line: isgx

- name: Install driver dependencies
  command: /sbin/depmod

- name: Install the driver
  command: /sbin/modprobe isgx
