---
- stat: path=/dev/isgx
  register: sgx_installed

- block:

    - name: Include "{{ ansible_os_family }}" SGX tasks
      include_tasks: "{{ ansible_os_family }}.yaml"

    - name: Install driver
      include_tasks: install.yml

  when: not sgx_installed.stat.exists
