- name: Install pre-requisites
  yum:
    name:
    - make
    - gcc

- name: Install pre-requisites RHEL 8
  yum:
    name: elfutils-libelf-devel
  when: ansible_distribution_major_version|int >= 8

- name: Chek if matching kernel headers are installed 
  stat:
    path: /usr/src/kernels/{{ ansible_kernel }}
  register: kernel_headers

- name: Instal kernel headers
  block:

  - name: Install kernel-devel-{{ ansible_kernel }}
    yum:
      name: kernel-devel-{{ ansible_kernel }}
    ignore_errors: yes
    register: kernel_install

  - name: Install last version of kernel and kernel headers and reboot
    block:

    - name: Install kernel-devel and kernel
      yum:
        name:
        - kernel-devel
        - kernel
        state: latest

    - name: Reboot the machine
      reboot:

    - name: refresh facts
      setup:

    when: kernel_install is failed

  when: not kernel_headers.stat.exists


